### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/federated/data/corpus_80000.pt.tar'

### ISSUE THREAD

**Issue by sjw1230** [ebagdasa/federated_adaptation#2]
Excuse me，what is the corpus_80000.pt.tar?I am a green hand,Thank you very much!

**Comment by sjw1230** [comment]
I have downloaded the text.json,shard_by_author.zip and the word_dictionary.pt?But when i run training.py,another error occured,it is that is no file named "corpus_80000.pt.tar".

**Comment by ebagdasa** [comment]
set  param 'recreate_dataset' to True

**Comment by ydtydr** [comment]
yeah, at the first time running the code, you need to create the training data (the corpus file) using the shard_by_author.zip, that's to say, just set the recreate_dataset option in yaml file to true, after you creating the corpus file, you can turn off the option.
